# Generated by Django 5.2.15 on 2026-06-14 16:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/categories/"
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_commission_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="e.g., Mens=2%, Kids=3%, Ladies=4%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "db_table": "products_category",
                "unique_together": {("company", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sku_prefix", models.CharField(blank=True, max_length=20)),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True, help_text="HSN code for GST", max_length=10
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "mrp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("minimum_order_qty", models.PositiveIntegerField(default=1)),
                ("order_in_multiples", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_stock", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "products_product",
            },
        ),
        migrations.CreateModel(
            name="ColorVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("color_name", models.CharField(max_length=100)),
                ("color_hex", models.CharField(blank=True, max_length=7)),
                (
                    "color_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/products/colors/"
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/products/qr/"
                    ),
                ),
                (
                    "qr_data",
                    models.TextField(
                        blank=True, help_text="JSON payload encoded in QR"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_color_variant",
                "unique_together": {("product", "color_name")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="media/products/%Y/%m/")),
                ("is_primary", models.BooleanField(default=False)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_image",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SizeChart",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sizes", models.JSONField(default=list)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "products_size_chart",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="size_chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.sizechart",
            ),
        ),
        migrations.CreateModel(
            name="VariantSize",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size", models.CharField(max_length=20)),
                ("sku", models.CharField(max_length=60, unique=True)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                (
                    "reserved_qty",
                    models.IntegerField(
                        default=0, help_text="Reserved for pending orders"
                    ),
                ),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.colorvariant",
                    ),
                ),
            ],
            options={
                "db_table": "products_variant_size",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out (Sale)"),
                            ("adjustment", "Manual Adjustment"),
                            ("return", "Customer Return"),
                            ("reserve", "Reserved (Order)"),
                            ("release", "Released (Cancelled)"),
                            ("damage", "Damaged/Written Off"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Positive = in, Negative = out"),
                ),
                ("balance_after", models.IntegerField()),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="products.variantsize",
                    ),
                ),
            ],
            options={
                "db_table": "products_stock_movement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "status"], name="products_pr_company_3b138a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantsize",
            unique_together={("color_variant", "size")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["variant_size", "created_at"],
                name="products_st_variant_2958c2_idx",
            ),
        ),
    ]
