# Generated by Django 5.2.15 on 2026-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colorvariant",
            name="color_image",
        ),
        migrations.AddField(
            model_name="colorvariant",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/products/variants/"
            ),
        ),
        migrations.AddField(
            model_name="colorvariant",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
