# Generated by Django 5.2.15 on 2026-08-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_colorvariant_color_image_colorvariant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariant',
            name='qr_data',
        ),
    ]
