# Generated by Django 5.2.15 on 2026-09-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_deleted_at_company_is_deleted_and_more'),
        ('products', '0005_alter_product_mrp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
