# Generated by Django 5.2.15 on 2026-09-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_deleted_at_company_is_deleted_and_more'),
        ('products', '0006_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
    ]
