# Generated by Django 5.2.15 on 2026-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
    ]
