# Generated by Django 5.2.15 on 2026-09-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_image_alter_colorvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='variantsize',
            name='is_active',
        ),
    ]
