# Generated by Django 5.2.15 on 2026-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packed_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity actually packed. May be less than ordered quantity.'),
        ),
    ]
