# Generated by Django 5.2.15 on 2026-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_packed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersignature',
            name='signature_image',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
