# Generated by Django 5.2.15 on 2026-09-09 10:36

from django.db import migrations, models


def remap_removed_statuses(apps, schema_editor):
    """Remap orders/history rows still holding removed status values."""
    Order = apps.get_model("orders", "Order")
    OrderStatusHistory = apps.get_model("orders", "OrderStatusHistory")

    status_map = {
        "draft": "submitted",
        "ready": "packed",
        "on_hold": "confirmed",
    }

    for old, new in status_map.items():
        Order.objects.filter(status=old).update(status=new)
        OrderStatusHistory.objects.filter(from_status=old).update(from_status=new)
        OrderStatusHistory.objects.filter(to_status=old).update(to_status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordersignature_signature_image'),
    ]

    operations = [
        migrations.RunPython(remap_removed_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
