# Generated by Django 5.2.15 on 2026-09-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='po_number',
        ),
    ]
