# Generated by Django 5.2.15 on 2026-06-14 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15)),
                ('gstin_verified', models.BooleanField(default=False)),
                ('gstin_legal_name', models.CharField(blank=True, max_length=200)),
                ('gstin_status', models.CharField(blank=True, max_length=50)),
                ('gstin_type', models.CharField(blank=True, max_length=50)),
                ('gstin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('billing_address_line1', models.CharField(blank=True, max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_pincode', models.CharField(blank=True, max_length=10)),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_pincode', models.CharField(blank=True, max_length=10)),
                ('same_as_billing', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_utilized', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('auto_block_on_exceed', models.BooleanField(default=True)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overdue_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('segment', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('prospect', 'Prospect')], default='active', max_length=15)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='agents.agentprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_profile',
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('gst_cert', 'GST Certificate'), ('pan_card', 'PAN Card'), ('aadhar', 'Aadhar Card'), ('trade_lic', 'Trade License'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='customer/docs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'customers_document',
            },
        ),
        migrations.CreateModel(
            name='CustomerCommunicationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Phone Call'), ('visit', 'Visit'), ('sms', 'SMS')], max_length=15)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'customers_communication_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['company', 'status'], name='customers_p_company_fd0068_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['gstin'], name='customers_p_gstin_4ea08c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['assigned_agent'], name='customers_p_assigne_9a5f99_idx'),
        ),
    ]
