# Generated by Django 5.2.15 on 2026-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_update_customer_profile_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
    ]
