# Generated by Django 5.2.15 on 2026-06-14 16:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/company/logos"
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "gstin",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("gstin_verified", models.BooleanField(default=False)),
                ("gstin_legal_name", models.CharField(blank=True, max_length=200)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=15)),
                ("website", models.URLField(blank=True)),
                ("invoice_prefix", models.CharField(default="INV", max_length=10)),
                ("po_prefix", models.CharField(default="PO", max_length=10)),
                ("invoice_counter", models.PositiveIntegerField(default=0)),
                ("po_counter", models.PositiveIntegerField(default=0)),
                ("financial_year_start", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account", models.CharField(blank=True, max_length=20)),
                ("bank_ifsc", models.CharField(blank=True, max_length=11)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("upi_id", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("grace", "Grace Period"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("tally_enabled", models.BooleanField(default=False)),
                (
                    "tally_url",
                    models.URLField(blank=True, help_text="Tally HTTP gateway URL"),
                ),
                ("tally_company", models.CharField(blank=True, max_length=200)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("gst_verify_enabled", models.BooleanField(default=False)),
                ("impersonation_token", models.CharField(blank=True, max_length=64)),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "companies_company",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_auto_confirm", models.BooleanField(default=False)),
                ("order_approval_required", models.BooleanField(default=True)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("credit_block_on_exceed", models.BooleanField(default=True)),
                ("notify_order_whatsapp", models.BooleanField(default=True)),
                ("notify_order_email", models.BooleanField(default=True)),
                ("notify_low_stock", models.BooleanField(default=True)),
                ("notify_payment_due_days", models.JSONField(default=list)),
                (
                    "commission_cycle",
                    models.CharField(default="monthly", max_length=20),
                ),
                ("commission_pay_day", models.PositiveSmallIntegerField(default=5)),
                (
                    "default_gst_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("reverse_charge", models.BooleanField(default=False)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "companies_settings",
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["status"], name="companies_c_status_2407e4_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["gstin"], name="companies_c_gstin_0d02df_idx"),
        ),
    ]
