# Generated by Django 5.2.15 on 2026-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_deleted_at_company_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='analytics_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='api_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='current_plan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='current_plan_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='custom_domain_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='dedicated_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='offline_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='plan_max_agents',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='plan_max_customers',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='plan_max_orders_per_month',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='plan_max_products',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='plan_storage_gb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
