# Generated by Django 5.2.15 on 2026-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/'),
        ),
    ]
