# Generated by Django 5.2.15 on 2026-09-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_generated_at',
        ),
    ]
