# Generated by Django 5.2.15 on 2026-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tally_synced_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tally_voucher_id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('void', 'Void')], default='draft', max_length=15),
        ),
    ]
