# Generated by Django 5.2.15 on 2026-09-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_unused_invoice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_order', 'Purchase Order'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=20),
        ),
    ]
