# Generated by Django 5.2.15 on 2026-06-14 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lr_number', models.CharField(blank=True, max_length=50)),
                ('transport_name', models.CharField(blank=True, max_length=200)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('driver_contact', models.CharField(blank=True, max_length=15)),
                ('dispatch_date', models.DateField()),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('tracking_url', models.URLField(blank=True)),
                ('eway_bill_no', models.CharField(blank=True, max_length=20)),
                ('boxes_count', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='orders.order')),
            ],
            options={
                'db_table': 'dispatch_dispatch',
            },
        ),
    ]
