# Generated by Django 5.2.15 on 2026-06-14 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("yearly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("trial_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "max_agents",
                    models.PositiveIntegerField(
                        default=3, help_text="0 = unlimited (Enterprise)"
                    ),
                ),
                (
                    "max_customers",
                    models.PositiveIntegerField(default=100, help_text="0 = unlimited"),
                ),
                (
                    "max_products",
                    models.PositiveIntegerField(default=500, help_text="0 = unlimited"),
                ),
                (
                    "max_orders_per_month",
                    models.PositiveIntegerField(default=200, help_text="0 = unlimited"),
                ),
                (
                    "storage_gb",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Storage in GB for product images and documents",
                    ),
                ),
                ("tally_sync_enabled", models.BooleanField(default=False)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("gst_verify_enabled", models.BooleanField(default=False)),
                ("analytics_advanced", models.BooleanField(default=False)),
                ("offline_mode_enabled", models.BooleanField(default=False)),
                ("api_access_enabled", models.BooleanField(default=False)),
                ("custom_domain_enabled", models.BooleanField(default=False)),
                ("dedicated_support", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "subscriptions_plan",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("grace", "Grace Period"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="trial",
                        max_length=15,
                    ),
                ),
                ("trial_start", models.DateField(blank=True, null=True)),
                ("trial_end", models.DateField(blank=True, null=True)),
                ("current_period_start", models.DateField(blank=True, null=True)),
                ("current_period_end", models.DateField(blank=True, null=True)),
                ("grace_period_end", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("engagement_score", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_subscription",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                            ("renewed", "Renewed"),
                            ("suspended", "Suspended"),
                            ("grace", "Grace Period Started"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("extended", "Extended (Manual)"),
                            ("reactivated", "Reactivated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "to_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_month",
                    models.DateField(help_text="First day of the month"),
                ),
                ("agent_count", models.PositiveIntegerField(default=0)),
                ("customer_count", models.PositiveIntegerField(default=0)),
                ("product_count", models.PositiveIntegerField(default=0)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("storage_used_mb", models.FloatField(default=0.0)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_snapshots",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_usage_snapshot",
                "ordering": ["-snapshot_month"],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="subscriptio_status_3d1ac5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usagesnapshot",
            unique_together={("subscription", "snapshot_month")},
        ),
    ]
