# Generated by Django 5.2.15 on 2026-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
