name: Dev
variables:
  - name: BASE_URL
    value: https://beta.xlapparals.in/api
  - name: ACCESS
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTQwMTA3LCJpYXQiOjE3ODc0NTM3MDcsImp0aSI6Ijc5MmRkMGYzYzljYzRhMzQ5NDQ1NzRiOTA2YmRmYWIyIiwidXNlcl9pZCI6IjlmMGM4MmJlLTE1YjMtNGM3Zi1iMmI1LTIwNjg4YWJmMWIyYyIsInJvbGUiOiJhZG1pbiIsImNvbXBhbnlfaWQiOiIzNDU0OGE4Yi0zMzIyLTQ0ZjMtYWQ5Yi00OGJhNGU0MDI3OGMiLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2V9.C2VcZgXOH6ItpJdqaCYlx-7QAyufYOX1ztOY9krXu3I
