name: Dev
variables:
  - name: baseUrl
    value: http://localhost:8000
  - name: AGENT_ACCESS
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5Mjc3OTAyLCJpYXQiOjE3ODkxOTE1MDIsImp0aSI6IjBiODZhYTA0NDUyYjQ4MDQ5N2I1MmQ0YjZmMjM2ZDU0IiwidXNlcl9pZCI6IjkxNWE1M2ZkLTI2Y2EtNDkwYy1iODVjLTU2Mzk3NGM4ZjIyZSIsInJvbGUiOiJhZ2VudCIsImNvbXBhbnlfaWQiOm51bGwsImlzX3N1cGVyX2FkbWluIjpmYWxzZX0.PTeoJmCZ-jUZgshr6u-gGFBKA3wXy5l-lb1TLvwq-Y4
  - name: AGENT_REFRESH
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc5MDUxOTY3OCwiaWF0IjoxNzg3OTI3Njc4LCJqdGkiOiIzMzdlZmYwYjE3ZmI0N2NkYjM4YjllMDNlYzdjYjA5NyIsInVzZXJfaWQiOiI5NDk2NWEyNy04OWEzLTQ0M2ItOTljOC0wOGRhYTRiNjFlZDMiLCJyb2xlIjoiYWdlbnQiLCJjb21wYW55X2lkIjpudWxsLCJpc19zdXBlcl9hZG1pbiI6ZmFsc2V9.16AayJ36dzj3Blys7nWBbhony6D_DNxQcZ3MGCCYN2c
  - name: ACCESS
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5Mjc3OTAyLCJpYXQiOjE3ODkxOTE1MDIsImp0aSI6IjBiODZhYTA0NDUyYjQ4MDQ5N2I1MmQ0YjZmMjM2ZDU0IiwidXNlcl9pZCI6IjkxNWE1M2ZkLTI2Y2EtNDkwYy1iODVjLTU2Mzk3NGM4ZjIyZSIsInJvbGUiOiJhZ2VudCIsImNvbXBhbnlfaWQiOm51bGwsImlzX3N1cGVyX2FkbWluIjpmYWxzZX0.PTeoJmCZ-jUZgshr6u-gGFBKA3wXy5l-lb1TLvwq-Y4
  - name: SUPERADMIN_ACCESS
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg5MDA2MDczLCJpYXQiOjE3ODg5MTk2NzQsImp0aSI6IjM3ZTU5ZDY3OTRlNDRiM2Q4OWFmN2Y0MmEzNGMxZTRmIiwidXNlcl9pZCI6ImYzMGE2YzI4LTQ5MDAtNDYwOS1hOTcyLWRlMDk2OTcyZWRlNCIsInJvbGUiOiJzdXBlcmFkbWluIiwiY29tcGFueV9pZCI6bnVsbCwiaXNfc3VwZXJfYWRtaW4iOnRydWV9.CIZkiYQ8Lb0Bs1uTF_ohH_MAWcH5TKYAqHbHb368QOQ
  - name: COMPANY_ID
    value: 36e6aadf-2a1e-4113-a448-853c73d99236
