# Generated by Django 5.2.15 on 2026-06-14 16:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("companies", "0001_initial"),
        ("customers", "0001_initial"),
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("neft", "NEFT / RTGS"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=100)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="media/payments/receipts/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_from_tally", models.BooleanField(default=False)),
                ("tally_ref", models.CharField(blank=True, max_length=100)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agents.agentprofile",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="OutstandingAging",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "current",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "days_1_30",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "days_31_60",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "days_61_90",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "days_90_plus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aging_records",
                        to="customers.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "payments_outstanding_aging",
                "ordering": ["-report_date"],
                "unique_together": {("company", "customer", "report_date")},
            },
        ),
    ]
