# Generated by Django 4.2.24 on 2026-06-29 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentcompanymembership",
            name="invitation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("qr_code", "QR Code"),
                    ("in_app", "In-App"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="agentcompanymembership",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentcompanymembership",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agentcompanymembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("reviewed", "Reviewed by Sub Admin"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("removed", "Removed"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
