# Generated by Django 5.2.15 on 2026-08-31 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agentinvitation_accepted_by_and_more'),
        ('companies', '0003_company_deleted_at_company_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCreditLimit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_utilized', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_credit_blocked', models.BooleanField(default=False)),
                ('auto_block_on_exceed', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_limits', to='agents.agentprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
            ],
            options={
                'db_table': 'agents_credit_limit',
                'constraints': [models.UniqueConstraint(fields=('company', 'agent'), name='unique_agent_credit_per_company')],
            },
        ),
    ]
