# apps/invoicing/urls.py

from django.urls import path

from apps.invoices.views import InvoiceViewSet

app_name = "invoicing"

urlpatterns = [
    # ─────────────────────────────────────────────────────────────
    # INVOICES
    # ─────────────────────────────────────────────────────────────
    # GET    /api/invoices/                      List invoices
    #          ?type=sales_invoice|purchase_order|credit_note|debit_note
    #          ?status=draft|issued|paid|partial|overdue|void
    #          ?customer_id=   ?overdue=true
    #          ?date_from=     ?date_to=
    #          ?search=<invoice_number|customer_name>
    # POST   /api/invoices/                      Create manual credit/debit note
    #          NOTE: Sales invoices + POs are auto-generated by the dispatch
    #          and order services — not via this endpoint.
    #
    # GET    /api/invoices/<pk>/                 Full invoice detail with line items
    # POST   /api/invoices/<pk>/void/            Void invoice (blocked if payments exist)
    # POST   /api/invoices/<pk>/regenerate-pdf/  Queue background PDF regeneration
    # GET    /api/invoices/<pk>/download/         Get PDF download URL
    path(
        "invoices/",
        InvoiceViewSet.as_view({"get": "list", "post": "create"}),
        name="invoice-list-create",
    ),
    path(
        "invoices/<uuid:pk>/",
        InvoiceViewSet.as_view({"get": "retrieve"}),
        name="invoice-detail",
    ),
    path(
        "invoices/<uuid:pk>/void/",
        InvoiceViewSet.as_view({"post": "void"}),
        name="invoice-void",
    ),
    path(
        "invoices/<uuid:pk>/regenerate-pdf/",
        InvoiceViewSet.as_view({"post": "regenerate_pdf"}),
        name="invoice-regenerate-pdf",
    ),
    path(
        "invoices/<uuid:pk>/download/",
        InvoiceViewSet.as_view({"get": "download"}),
        name="invoice-download",
    ),
]
